### ISSUE TITLE
Huawei T1-821L tablet is not working with the newest release

### ISSUE THREAD

**Issue by DenielTorres** [thanksmister/wallpanel-android-legacy#1]
**Describe the bug**
With the newest release, the wallpanel only shows the header for a home assistant/tileboard instance (see screenshot below).

**To Reproduce**
N/A

**Expected behavior**
I pulled the latest legacy update (v0.8.4-beta.7) and now it has the same issues as when I try with the non-legacy version. I was expecting to have the updates. 

**Screenshots**
https://www.dropbox.com/s/zabl19jfbfn1ng1/wallpanel_screen.jpeg?dl=0 

**Smartphone (please complete the following information):**
 - Device: Huawei T1-821L tablet
 - OS: Android 4.4.4

**Additional context**
It was working flawlessly with one of the previous releases. I tried to find earlier version apk files but couldn't. Thanks in advance!

**Comment by thanksmister** [comment]
Nothing has changed in the way web pages are rendered.  The application uses Googles WebView component which is solely responsible for rendering the web page.  The version of this component is based on your devices OS version.   What probably happened is that the page was refreshed after the update and changes that were recently made changed the rendering of the page.  There is nothing I can offer to fix the situation since it’s a compatibility issue with the page and Googles WebView component.

**Comment by DenielTorres** [comment]
Thanks, @thanksmister for the explanation! I'll investigate on my end what could have caused this. Cheers to your good work!
