### ISSUE TITLE
Wallpanel for Android 4.0.4

### ISSUE THREAD

**Issue by donmueang** [thanksmister/wallpanel-android-legacy#6]
As there are still a lot of old tablets running Android 4.0.4

Is there a way to use Wallpanel on those devices?

**Comment by thanksmister** [comment]
No because even though those devices are still around, the software for building software for them has moved on.  The other issue is that web technologies have also moved on, so the software that a 4.0.4 device has for making apps for rendering web pages isn't compatible with Lovelace.   If you want, you can try Fully Kiosk Browser or some other type of web rendering application.

**Comment by MrMuzzio** [comment]
If you'd like to use the tablet for Homeassistant, yo may try Tileboard (https://github.com/resoai/TileBoard) and the legacy version of Wallpanel (https://github.com/thanksmister/wallpanel-android-legacy). Thanks to @thanksmister  you can still download and install it.

I would recommend using a Long-Lived Access Token (https://www.home-assistant.io/docs/authentication/) since the new Lovelace login has some issues with old web components.

**Comment by thanksmister** [comment]
@MrMuzzio thanks for that advice, good suggestions!

**Comment by KALRONG** [comment]
@MrMuzzio thanks for the info! Can you please elavorate on the Long lived access token? I read the doc but cant figure out how to use it on wallpanel-legacy

**Comment by MrMuzzio** [comment]
Hi! Glad to help! 
You should generate a long-lived access token in Home Assistant and use it within TileBoard (https://github.com/resoai/TileBoard).
Once you have Tileboard up and running from your PC, you have to edit the file "config.js" and put your "long-lived access token"  replacing the word "null" in the line that reads " authToken: null," Keep in mind you need to keep the colon "," for this to work.
Hope that works for you too!
